In [39]:
# Basic numpy operations

import numpy as np

In [40]:
squares = [n**2 for n in range(0, 10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [41]:
# creating numpy array using a list
np.array(squares)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [42]:
# matrix of zeros
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [43]:
# matrix of ones
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [47]:
# identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [44]:
# get linearly separated points (start, end, no of points)
points = np.linspace(1, 50, 50)
points

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.])

In [9]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [45]:
# generate random integers in the given range (start, end, no of random numbers to be generated)
np.random.randint(1,50,5)

array([18, 44,  3, 15, 16])

In [12]:
arr = np.array([[10, 21, 3], [42, 5, 6], [12, 18, 27]])

In [13]:
arr.max()

42

In [14]:
arr

array([[10, 21,  3],
       [42,  5,  6],
       [12, 18, 27]])

In [38]:
# extracting segments
t = arr[1:,1:]
t

array([[ 5,  6],
       [18, 27]])

In [16]:
# to get array dimensions
t.shape

(2, 2)

In [17]:
t

array([[ 5,  6],
       [18, 27]])

In [37]:
# Boolean mask
t > 5

array([[False,  True],
       [ True,  True]], dtype=bool)

In [34]:
# Boolean mask
temp = t[t > 5]
temp

array([ 6, 18, 27])

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
b = np.array([[2], [4], [6]])
b

array([[2],
       [4],
       [6]])

In [22]:
c = np.array([[1], [3], [5], [7]])
c

array([[1],
       [3],
       [5],
       [7]])

In [23]:
a * b

array([[ 2,  4,  6],
       [16, 20, 24],
       [42, 48, 54]])

In [29]:
# arange function
# get a range of numbers starting from 1 to 11 (non-inclusive) with a step of 1
a = np.arange(1,11,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
b = np.arange(10,0,-1)
b

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
# reshaping a matrix
# 1x25 row vector is reshaped to 5x5 matrix
c = np.arange(1,26,1)
c = c.reshape(5,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])